FROM chromadb/chroma:1.5.0

ENV IS_PERSISTENT=TRUE
ENV ANONYMIZED_TELEMETRY=false
ENV CHROMA_HOST_ADDR=::
ENV CHROMA_HOST_PORT=8000
ENV PORT=8000
ENV CHROMA_WORKERS=1
ENV CHROMA_TIMEOUT_KEEP_ALIVE=30
